dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  # organisation/repository/verison
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      # remapping because when deploying our 
      # sol file it cant get the @chainlink
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  ganache-local:
    verify: False
  development:
    verify: False
